### PR TITLE
Integrate Mayhem

### PR DESCRIPTION
**Pull request by rnshah9**

### CODE REVIEW

**Review by xansec — APPROVED** [review]
LGTM!

**Comment by xansec** [comment]
@rnshah9 It appears the latest action is failing. Please take a look:
https://github.com/mayhemheroes/daScript/actions/runs/3746374518

**Comment by rnshah9** [comment]
Looks like upstream changes broke the build. Made #2 to patch, but it may break the build again when upstream is fixed.

**Comment by xansec** [comment]
Great, merged. Thanks

**Pull request merged**
